name: Chat-PP
on: push
jobs:
  testScripts:
    name: Test scripts
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: |
          echo "${{ env.BBB_BRANCH }}"
          echo ${GITHUB_REF#refs/*/}
          BB_BRANCH=${GITHUB_REF#refs/*/}
          echo $BB_BRANCH
          echo "BBB_BRANCH=$BB_BRANCH" >> $GITHUB_ENV
          echo "BBB"
          echo "${{ env.BBB_BRANCH }}"
          echo $GITHUB_REF_NAME

      - name: The next episode
        run: |
          echo ${{ env.BBB_BRANCH }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        working-directory: packages/scripts
        run: npm install

      - name: Test scripts
        working-directory: packages/scripts
        run: npm run test

  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Terraform
        run: |
          echo "Will run infrastructure!!!"

  buildScripts:
    name: Build scripts
    runs-on: ubuntu-latest
    needs: ["testScripts"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        working-directory: packages/scripts
        run: npm install

      - name: Build scripts
        working-directory: packages/scripts
        run: npm run build

      - name: Copy over project files
        working-directory: packages/scripts
        run: |
          cp package.json ./build
          cd ./build
          npm install --only=prod

      - name: Archive build scripts
        uses: actions/upload-artifact@v2
        with:
          name: builtScripts
          path: packages/scripts/build

  changes:
    name: Determine changes
    runs-on: ubuntu-latest
    needs: ["buildScripts"]
    outputs:
      BUILD_LAMBDA_FUNCTIONS: ${{ steps.changes.outputs.BUILD_LAMBDA_FUNCTIONS }}
      JSON_STRING: ${{ steps.changes.outputs.JSON_STRING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download built scripts
        uses: actions/download-artifact@v2
        with:
          name: builtScripts
          path: ./builtScripts

      - name: Node script set env variables.
        run: |
          node builtScripts/setEnvVariables.js

      - name: The next Node episode.
        run: |
          echo "chat-message -> ${{ env.LAMBDA_FUNCTIONS_chat-message }}"
          echo ${{ env.LAMBDA_FUNCTIONS_chat-message }}
          echo ${{ env.LAMBDA_FUNCTIONS_chat-broadcast }}
          echo "chat-broadcast -> ${{ env.LAMBDA_FUNCTIONS_chat-broadcast }}"
          node builtScripts/passArgs.js ${{ env.LAMBDA_FUNCTIONS_chat-broadcast }} ${{ env.LAMBDA_FUNCTIONS_chat-message }}

      - name: See changes
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }} >> changes.txt
          node builtScripts/determineChanges.js

  buildLambdaFunctions:
    name: Build Lambda Functions
    needs: ["changes"]
    if: ${{ needs.changes.outputs.BUILD_LAMBDA_FUNCTIONS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Only run if Lambda Functions need building
        run: |
          echo "Building Lambda Functions"
          echo ${{ needs.changes.outputs.BUILD_LAMBDA_FUNCTIONS }}
          echo ${{ needs.changes.outputs.JSON_STRING }}

      - name: Download built scripts
        uses: actions/download-artifact@v2
        with:
          name: builtScripts
          path: ./builtScripts

      - name: Node json
        run: |
          sudo apt-get install -y jq
          echo ${{ toJSON(needs.changes.outputs.JSON_STRING) }} | jq . | node builtScripts/passArgs.js

  buildLambdaFunctionsLayer:
    name: Build Lambda Functions Layer
    needs: ["changes"]
    if: ${{ needs.changes.outputs.BUILD_LAMBDA_FUNCTIONS_LAYER == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Only run if the Lambda Functions layer needs to be rebuilt
        run: |
          echo "Rebuilding layer"
