name: Chat-PP
on: push
jobs:
  changes:
    name: Gather changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: See changes
        run: node ./scripts/determineChanges.js
