name: Chat-PP
on: push
jobs:
  testScripts:
    name: Test scripts
    runs-on: ubuntu-latest
    steps:
      - name: The next episode
        run: |
          echo ${{ env.BBB_BRANCH }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        working-directory: packages/scripts
        run: npm install

      - name: Test scripts
        working-directory: packages/scripts
        run: npm run test

  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_CLI_PAGER: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform Infrastructure
        working-directory: ./terraform
        run: terraform plan

      - name: Provision Infrastructure
        working-directory: ./terraform
        run: terraform apply -auto-approve

  buildScripts:
    name: Build scripts
    runs-on: ubuntu-latest
    needs: ["testScripts"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        working-directory: packages/scripts
        run: npm install

      - name: Build scripts
        working-directory: packages/scripts
        run: npm run build

      - name: Copy over project files
        working-directory: packages/scripts
        run: |
          cp package.json ./build
          cd ./build
          npm install --only=prod

      - name: Archive build scripts
        uses: actions/upload-artifact@v2
        with:
          name: builtScripts
          path: packages/scripts/build

  changes:
    name: Determine changes
    runs-on: ubuntu-latest
    needs: ["buildScripts"]
    outputs:
      BUILD_LAMBDA_FUNCTIONS: ${{ steps.changes.outputs.BUILD_LAMBDA_FUNCTIONS }}
      BUILD_LAMBDA_FUNCTIONS_LAYER: ${{ steps.changes.outputs.BUILD_LAMBDA_FUNCTIONS_LAYER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download built scripts
        uses: actions/download-artifact@v2
        with:
          name: builtScripts
          path: ./builtScripts

      - name: See changes
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }} >> changes.txt
          node builtScripts/determineChanges.js
          cat changes.json

      - name: Upload changes
        uses: actions/upload-artifact@v2
        with:
          name: changes
          path: ./changes.json

  buildLambdaFunctions:
    name: Build Lambda Functions
    needs: ["changes", "infrastructure"]
    if: |
      ${{ github.ref == 'refs/heads/main' && needs.changes.outputs.BUILD_LAMBDA_FUNCTIONS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Download built scripts
        uses: actions/download-artifact@v2
        with:
          name: builtScripts
          path: ./builtScripts

      - name: Download changes.json
        uses: actions/download-artifact@v2
        with:
          name: changes

      - name: Run Build Lambda Functions scripts
        working-directory: ./packages/lambda-functions
        run: |
          node ./scripts/buildFunctions.js

  buildLambdaFunctionsLayer:
    name: Build Lambda Functions Layer
    needs: ["changes"]
    if: ${{ needs.changes.outputs.BUILD_LAMBDA_FUNCTIONS_LAYER == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Only run if the Lambda Functions layer needs to be rebuilt
        run: |
          echo "Rebuilding layer"
