name: Chat-PP
on: push
jobs:
  changes:
    name: Gather changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: See changes
        run: |
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }} >> changes.txt
          node ./scripts/determineChanges.js
